zq-server:
  name: hoppinzq-file
  username: zhangqi
  password: 123456
  prefix: /service
  ip: 127.0.0.1
  center-addr: http://127.0.0.1:8801/service
  #   center-addr: http://175.178.115.82:8801/service